name: Create env Secrets

on:
    push:
        branches:
            - main

jobs:
    create-secrets:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm install

            - name: Create .env file
              run: |
                echo "NEXT_PUBLIC_TEAM_ID=${{ secrets.NEXT_PUBLIC_TEAM_ID }}" >> .env
                echo "NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL }}" >> .env

            - name: Run Test
              run: npm run test

            - name: Run Build
              run: npm run build
      